steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/web-speed-hackathon-2026', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/web-speed-hackathon-2026']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'web-speed-hackathon-2026'
      - '--image'
      - 'gcr.io/$PROJECT_ID/web-speed-hackathon-2026'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--port'
      - '8080'
      - '--max-instances'
      - '1'
      - '--memory'
      - '2Gi'
      - '--set-env-vars'
      - 'NODE_ENV=production,PORT=8080'
      - '--allow-unauthenticated'
images:
  - 'gcr.io/$PROJECT_ID/web-speed-hackathon-2026'
